In [2]:
import torch  
import numpy as np 
import random

# Tensor Creation: Create a 2D tensor of size (4, 5) with random integers ranging from 0 to 50.

In [4]:
#torch.randint(low, high, size): Creates a tensor filled with random integers from low (inclusive) to high (exclusive).
#0 is the lower bound (inclusive).
#51 is the upper bound (exclusive) to include numbers up to 50.
#(4, 5) specifies the desired shape of the tensor.
tensor1=torch.randint(0,51,(4,5))

# Tensor Reshaping: Given a tensor of size (3, 4, 2), reshape it to a tensor of size (2, 3, 4). Verify the total number of elements remains the same.

In [7]:
# tensor creation
tensor2=torch.randint(0,51,(3,4,2))
#tensor reshaping 
tensor2_reshaped=tensor2.reshape(2,3,4)

#getting number of elements in tensor2 and reshaped tensor using .numel 
#The .numel() method in PyTorch is used to calculate the total number of elements in a tensor.
ntensor2=tensor2.numel()
ntensor2reshaped=tensor2_reshaped.numel()
if ntensor2 ==ntensor2reshaped: 
    print("Elements same in number.")
else: 
    print("Shata")

Elements same in number.


# Dimension Information: Create a 3D tensor of size (2, 3, 4). Write a function that takes any tensor as input and returns its number of dimensions, shape, and total number of elements.

In [8]:
def tensor_info(tensor):
    dim=tensor.ndim
    shape=tensor.shape
    nele=tensor.numel() 
    return dim,shape,nele

dimension,shape,nelements=tensor_info(tensor2_reshaped)
print(dimension,shape,nelements)

3 torch.Size([2, 3, 4]) 24


# Scalar Operations: Create a tensor of size (5, 5) filled with the value 10. Multiply each element of this tensor by 0.5, then add 5 to each element.

In [12]:
tensor=torch.randint(0,10,(5,5))
print(tensor)
tensormul=tensor.mul(0.5)
print(tensormul)
tensorsum=tensormul+5
print(tensorsum)

tensor([[8, 0, 5, 3, 3],
        [3, 2, 7, 0, 5],
        [8, 7, 8, 4, 1],
        [7, 4, 1, 7, 2],
        [5, 1, 9, 0, 2]])
tensor([[4.0000, 0.0000, 2.5000, 1.5000, 1.5000],
        [1.5000, 1.0000, 3.5000, 0.0000, 2.5000],
        [4.0000, 3.5000, 4.0000, 2.0000, 0.5000],
        [3.5000, 2.0000, 0.5000, 3.5000, 1.0000],
        [2.5000, 0.5000, 4.5000, 0.0000, 1.0000]])
tensor([[9.0000, 5.0000, 7.5000, 6.5000, 6.5000],
        [6.5000, 6.0000, 8.5000, 5.0000, 7.5000],
        [9.0000, 8.5000, 9.0000, 7.0000, 5.5000],
        [8.5000, 7.0000, 5.5000, 8.5000, 6.0000],
        [7.5000, 5.5000, 9.5000, 5.0000, 6.0000]])


# Matrix Multiplication: Create two tensors of size (3, 4) and (4, 2). Perform matrix multiplication between them. Verify the resulting tensor's shape.

In [15]:
tens1=torch.randint(0,5,(3,4))
tens2=torch.randint(0,5,(4,2))
matmul=tens1@tens2
print(matmul)

tensor([[13, 20],
        [10, 22],
        [13, 22]])


# Element-wise Operations: Create two tensors of the same size (4, 4) with random values. Perform element-wise addition, subtraction, multiplication, and division between them.

In [19]:
tens1=torch.randint(0,5,(4,4))
print(tens1)
tens2=torch.randint(5,10,(4,4))
print(tens2)
print(tens1 + tens2)

print(tens1 - tens2)

print(tens1 * tens2)

print(tens1 / tens2)

tensor([[3, 0, 1, 3],
        [0, 1, 3, 1],
        [3, 0, 4, 4],
        [2, 0, 2, 4]])
tensor([[9, 7, 8, 8],
        [9, 7, 7, 5],
        [7, 7, 8, 6],
        [8, 6, 9, 6]])
tensor([[12,  7,  9, 11],
        [ 9,  8, 10,  6],
        [10,  7, 12, 10],
        [10,  6, 11, 10]])
tensor([[-6, -7, -7, -5],
        [-9, -6, -4, -4],
        [-4, -7, -4, -2],
        [-6, -6, -7, -2]])
tensor([[27,  0,  8, 24],
        [ 0,  7, 21,  5],
        [21,  0, 32, 24],
        [16,  0, 18, 24]])
tensor([[0.3333, 0.0000, 0.1250, 0.3750],
        [0.0000, 0.1429, 0.4286, 0.2000],
        [0.4286, 0.0000, 0.5000, 0.6667],
        [0.2500, 0.0000, 0.2222, 0.6667]])


# Indexing: Create a 3D tensor of size (4, 3, 2). Extract the tensor formed by the first 2 rows of the second dimension for all elements in the other dimensions.

In [20]:
#indexing basics

# Create a 2D tensor (4x4)
tensor_2d = torch.tensor([[1, 2, 3, 4],
                          [5, 6, 7, 8],
                          [9, 10, 11, 12],
                          [13, 14, 15, 16]])

# Access a specific element
element = tensor_2d[2, 3]  # Access the element in the 3rd row and 4th column
print("Element at (2, 3):", element)

# Access an entire row
row = tensor_2d[1, :]  # Access the 2nd row
print("Second row:", row)

# Access an entire column
column = tensor_2d[:, 2]  # Access the 3rd column
print("Third column:", column)

# Access a sub-tensor (slicing)
sub_tensor = tensor_2d[1:3, 1:3]  # Access the 2x2 sub-matrix
print("Sub-tensor (2x2):")
print(sub_tensor)

Element at (2, 3): tensor(12)
Second row: tensor([5, 6, 7, 8])
Third column: tensor([ 3,  7, 11, 15])
Sub-tensor (2x2):
tensor([[ 6,  7],
        [10, 11]])


In [22]:
#inedexing 3d tesnors 
'''
A 3D tensor can be visualized as a stack of matrices (2D tensors). Indexing involves specifying indices for three dimensions: [depth, row, column].

A 3D tensor can be thought of as a collection of 2D matrices stacked together, similar to how pages in a book are stacked. This stacking introduces an additional dimension, often called the depth or channel dimension, depending on the context.

How 3D Tensors Are Arranged
A 3D tensor in PyTorch has three dimensions that can be generalized as:

Depth (Channel/Stack) - This is the first dimension, representing the number of 2D matrices (slices) in the stack. Each slice is a 2D matrix.
Rows - The second dimension represents the number of rows in each 2D matrix.
Columns - The third dimension represents the number of columns in each 2D matrix.

import torch

# Creating a 3D tensor of size (2, 3, 4)
tensor_3d = torch.tensor([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print(tensor_3d.shape)  # Output: torch.Size([2, 3, 4])


Accessing Elements in a 3D Tensor
To access elements in a 3D tensor, you use three indices: [depth, row, column].

Example: Access Specific Elements
tensor_3d[0, 1, 2] accesses the element in the 1st slice, 2nd row, and 3rd column. In this case, it would be 7.
tensor_3d[1, 2, 3] accesses the element in the 2nd slice, 3rd row, and 4th column. In this case, it would be 24.

General Indexing Rules
Single Colon (:): Selects all elements along that dimension.
Slicing (start:stop:step): Similar to Python lists, can select a range of elements along a dimension.
Ellipsis (...): Can be used to select all elements of unspecified dimensions, e.g., tensor[..., 2] selects the 3rd element in the
 last dimension across all others.


'''

tens1=torch.randint(0,5,(4,3,2))
print(tens1)

#Extract the tensor formed by the first 2 rows of the second dimension for all elements in the other dimensions.
accesstensor=tens1[:,:2,:]

tensor([[[3, 0],
         [1, 2],
         [4, 1]],

        [[3, 0],
         [1, 0],
         [3, 0]],

        [[3, 0],
         [2, 3],
         [4, 2]],

        [[0, 2],
         [3, 4],
         [2, 1]]])


# Slicing: Given a tensor of shape (6, 6), slice out the center 2x2 block.

In [25]:
tens=torch.randint(0,5,(6,6))
slicedtens=tens[2:4,2:4]
print(slicedtens)

tensor([[0, 3],
        [2, 3]])


# Conditional Selection: Create a tensor of size (4, 4) with random values. Replace all elements greater than 0.5 with 1, and all elements less than or equal to 0.5 with 0.



In [33]:
'''
torch.where(condition, x, y):
Takes three arguments: a condition, x, and y.
Condition:  creates a boolean mask where each element is checked if it's greater than 0.5.
x: Value to replace where the condition is True (1 in this case).
y: Value to replace where the condition is False (0 in this case).

'''

tenss=torch.rand(4,4)
print(tenss)
tenss=tenss.where(tenss>0.5,0)
tenss=tenss.where(tenss<0.5,1)
print(tenss)

tensor([[0.2692, 0.8762, 0.3002, 0.3975],
        [0.3956, 0.7803, 0.0890, 0.5810],
        [0.1771, 0.6984, 0.4115, 0.1997],
        [0.6817, 0.6739, 0.0596, 0.5322]])
tensor([[0., 1., 0., 0.],
        [0., 1., 0., 1.],
        [0., 1., 0., 0.],
        [1., 1., 0., 1.]])


# Stacking: Create two 1D tensors of size 5 each. Stack them vertically and horizontally to form a 2D tensor.

# Stacking: Create two 1D tensors of size 5 each. Stack them vertically and horizontally to form a 2D tensor.

In [ ]:
# Create a 1-dimensional tensor of size 5 with random integers between 0 and 10
#tensor_1d = torch.randint(0, 10, (5,))
#torch.randint(low, high, size):
#low: The lower bound (inclusive) for random values.
#high: The upper bound (exclusive) for random values.
#size: The shape of the tensor. (5,) indicates a 1-dimensional tensor with 5 elements.

tensor1 = torch.tensor([1, 2, 3, 4, 5])
tensor2 = torch.tensor([6, 7, 8, 9, 10])

'''
torch.stack()
What It Does:
torch.stack() joins a sequence of tensors along a new dimension. This new dimension is specified by the dim parameter.
Unlike concatenation (torch.cat()), which joins tensors along an existing dimension, torch.stack() adds a new dimension,
 effectively "stacking" the tensors on top of each other.

Arguments:
tensors: A sequence (list or tuple) of tensors that you want to stack.
dim: The dimension along which to insert the new dimension. This argument is an integer, and it can range from 0 to the number 
of dimensions of the tensors.


Requirements:
All tensors in the input sequence must have the same shape.

torch.vstack()
What It Does:
torch.vstack() vertically stacks tensors (i.e., stacks them along the first dimension). It is similar to concatenating tensors 
along the rows.
It's equivalent to using torch.cat(tensors, dim=0) for 2D tensors.

Arguments:
tensors: A sequence of tensors to stack vertically.

Requirements:
The tensors must have the same number of columns (i.e., the same shape except in the first dimension).


torch.hstack()
What It Does:
torch.hstack() horizontally stacks tensors (i.e., stacks them along the second dimension). It is similar to concatenating tensors
 along the columns.
It’s equivalent to using torch.cat(tensors, dim=1) for 2D tensors.

Arguments:
tensors: A sequence of tensors to stack horizontally.

Requirements:
The tensors must have the same number of rows (i.e., the same shape except in the last dimension).


Differences Between Them
torch.stack():
Creates a new dimension to stack the tensors.
Requires specifying which dimension to insert (dim).
The input tensors must have the same shape.
torch.vstack():
Stacks tensors along the vertical axis (first dimension, like stacking rows).
Equivalent to torch.cat(tensors, dim=0) for 2D tensors.
Input tensors must have the same number of columns.
torch.hstack():
Stacks tensors along the horizontal axis (second dimension, like stacking columns).
Equivalent to torch.cat(tensors, dim=1) for 2D tensors.
Input tensors must have the same number of rows.

'''

stackedtensor=torch.stack((tensor1,tensor2),0)
print(stackedtensor)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


# Splitting: Given a tensor of size (8, 8), split it into four smaller tensors of size (4, 4).

In [ ]:
'''
Splitting a tensor means dividing a larger tensor into smaller sub-tensors along a specified dimension. This can be useful 
when processing data in chunks, applying operations to specific segments of data, or simply organizing data into more manageable
 pieces.

How to Split Tensors in PyTorch
PyTorch provides multiple functions to split tensors:

torch.split(): Splits a tensor into chunks of specified size(s) along a given dimension.
torch.chunk(): Divides a tensor into a specified number of equal-sized chunks along a given dimension.
1. Using torch.split()
torch.split(tensor, split_size_or_sections, dim=0):
tensor: The tensor to split.
split_size_or_sections: Specifies the size of each chunk or a list defining the sizes of each chunk.
dim: The dimension along which to split the tensor


2.Using torch.chunk()
torch.chunk(tensor, chunks, dim=0):
tensor: The tensor to split.
chunks: The number of chunks to split the tensor into.
dim: The dimension along which to split the tensor.

Where is Tensor Splitting Used?
Batch Processing: Splitting large batches of data into smaller batches for processing in neural networks.
Data Sharding: When working with distributed systems or parallel processing, data is split into smaller shards.
Cross-Validation: In machine learning, splitting data into folds for cross-validation.
Memory Management: To avoid memory overflow, large tensors are split into smaller ones that can be processed sequentially.
Chunk-wise Operations: Applying operations or functions to specific segments of data, such as processing different parts of an 
image separately.
Summary of Differences Between torch.split() and torch.chunk()
torch.split():
More flexible since you can specify the exact size of each chunk.
Can take a list of sizes, allowing non-uniform splitting.
torch.chunk():
Splits the tensor into a specific number of equal chunks.
If the size of the tensor is not perfectly divisible by the number of chunks, some chunks may be smaller than others.
Example for Clarity
torch.split(tensor, 2) splits into chunks of size 2.
torch.chunk(tensor, 4) splits the tensor into 4 equal-sized chunks.
'''

# Broadcasting: Create a tensor of shape (2, 3) and a 1D tensor of size 3. Add them together using broadcasting.

# Transpose: Create a tensor of size (3, 4). Swap its rows and columns using transpose, resulting in a tensor of size (4, 3).

# Concatenation: Create three tensors of size (3, 2). Concatenate them along the rows (first dimension) and columns (second dimension).

# Flattening: Given a 4D tensor of size (2, 3, 4, 5), flatten it to a 1D tensor. Verify the total number of elements is preserved.

# You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).

# torch.argmax()
What it does: Returns the index of the maximum value in a tensor. If you specify a dimension (or axis), it finds the index of the maximum value along that dimension.

Arguments:

input: The input tensor where the maximum values are to be found.

dim (optional): The dimension along which to find the maximum. If not provided, it returns the index of the maximum element in the flattened tensor.

keepdim (optional): If set to True, the output tensor retains the reduced dimension with size 1. Default is False.

# torch.argmin()
What it does: Returns the index of the minimum value in a tensor. Similar to argmax, it can return the index of the minimum value along a specified dimension or in the flattened tensor.

Arguments:

input: The input tensor where the minimum values are to be found.

dim (optional): The dimension along which to find the minimum. If not provided, it returns the index of the minimum element in the flattened tensor.

keepdim (optional): If set to True, the output tensor retains the reduced dimension with size 1. Default is False.

In [38]:
# you can directly call the argmax or argmin methods on a tensor object.
#  For example, if you have a tensor named tensor, you can use:

result_max = tensor.argmax()  # Calls the method on the tensor
result_min = tensor.argmin()  # Calls the method on the tensor
print(result_max)
print(result_min)

tensor(22)
tensor(1)


# Reproducability(Trying to take the random out of random)
In short how a neural network works start with random number -> tensor operations > update random numbers to try and make them better representations of the data -> again -> again -> again ...

PyTorch's rand() method, generated a random tensor for the given input dimension everytime. To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what the random seed does is "flavour the randomness.

In [39]:
import torch
# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8464, 0.2895, 0.4066, 0.5553],
        [0.6870, 0.8075, 0.3077, 0.4079],
        [0.6756, 0.2788, 0.9416, 0.7814]])
tensor([[2.0311e-01, 4.8787e-02, 7.2849e-04, 4.2267e-01],
        [6.5901e-01, 8.3514e-01, 6.3753e-01, 9.9646e-01],
        [3.3878e-01, 4.2426e-01, 7.4976e-01, 2.2712e-01]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [40]:
# we make the above tensors reproducable ,as follows

import torch

# set the random sees, commonly used value is 42
# You can set it to any number

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# A seed in the context of random number generation is an initial value that initializes a pseudo-random number generator (PRNG). PRNGs are algorithms that generate sequences of numbers that appear random but are actually deterministic, meaning that if you know the seed, you can predict the sequence. The seed value ensures that the sequence of "random" numbers is reproducible.

When you set a seed, you are essentially telling the random number generator to start at a specific point in its number generation process. This allows for reproducibility in experiments and code execution. If you run the same code multiple times with the same seed, you'll get the same sequence of random numbers every time, which is essential in many fields like machine learning and simulations for debugging and consistency.

# Running tensors and PyTorch objects on a GPU (Graphics Processing Unit) can significantly speed up computations, especially for large-scale deep learning tasks like training neural networks. This is because GPUs are optimized for parallel processing, which is highly beneficial when performing operations on large tensors or during matrix multiplications involved in deep learning.

# Why Run PyTorch Tensors on a GPU?
Speed: GPUs are highly efficient at performing many simple, similar operations in parallel. This makes them much faster for deep learning tasks and operations on large tensors compared to a CPU (which performs operations in a more sequential manner).

Efficient for Deep Learning: Deep learning models involve large amounts of matrix operations (like tensor multiplications and additions). GPUs can handle these operations much faster due to their ability to parallelize computations.

Massive Data Parallelism: The ability to handle thousands of parallel threads makes GPUs ideal for tasks that can be broken down into smaller independent units of work, like deep learning.

# How to Run Tensors and PyTorch Objects on a GPU?
PyTorch makes it easy to move tensors and models between the CPU and GPU. Below are the steps to do this.



In [41]:
'''
Checking GPU Availability:
Before you can run your tensors on a GPU, you should check if a GPU is available on your machine:
'''

torch.cuda.is_available()

'''
If the output is True, then you have a CUDA-enabled GPU available for use. If it returns False, PyTorch will continue using the 
CPU for computations.
'''

False

In [ ]:
# Moving Tensors to a GPU:
#To move a tensor to the GPU, you need to specify that the tensor should be stored on the GPU using the .to() or .cuda() method. 
cpu_tensor = torch.tensor([1, 2, 3])

# Move the tensor to GPU
gpu_tensor = cpu_tensor.to('cuda')
# Or alternatively using .cuda()
gpu_tensor = cpu_tensor.cuda()

#Moves the tensor to the default GPU (if you have multiple GPUs).

In [ ]:
'''
 Creating a Tensor Directly on the GPU:
You can create a tensor directly on the GPU by specifying the device parameter when creating the tensor:
'''
gpu_tensor = torch.tensor([1, 2, 3], device='cuda')


In [ ]:
# Moving a Model to the GPU:
#When training a neural network, it's important to move both the model and data to the GPU. You can do this for a model using the 
# .to('cuda') method.

model = MyModel()

# Move the model to GPU
model = model.to('cuda')
input_tensor = torch.randn(10, 3).to('cuda')

# Forward pass (runs on GPU)
output = model(input_tensor)

In [ ]:
''' 
Moving Tensors Back to the CPU:
After performing computations on the GPU, you might want to move the results back to the CPU for further processing or to save 
memory on the GPU.

# Move the tensor back to CPU
cpu_tensor = gpu_tensor.to('cpu')
print(cpu_tensor)

'''